### ISSUE TITLE
Horses list - GUI

### ISSUE THREAD

**Issue by SeussCZ** [zPikaa/PocketHorses#2]
1. Horses in the GUI are listed randomly, it will be great to make this list more logically sorted (by price for example).

2. Can you add command for buying specific horse? For buing from NPC for example.

3. Horse armour dissapear when horse is removed and again spawned.

4. When you are on the horse and changing regions (perhaps) "shift" didnt work, and player is stuck on the horse.

**Comment by zPikaa** [comment]
Hi, thanks for reporting these problems and proposing these functions. It will all be implemented in the next update
